#GATEWAY'S CONFIG
server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://${LINK_DB_URI}/postservice
    password: ${LINK_DB_PASSWORD}
    username: ${LINK_DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

  application:
    name: postservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id:  ${spring.application.name}:${random.value}
    preferIpAddress: true

