#GATEWAY'S CONFIG
server:
  port: 0
spring:
  application:
    name: postservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id:  ${spring.application.name}:${random.value}
    preferIpAddress: true


      spring:
        datasource:
          url: jdbc:postgresql://${TRAINING_DB_ENDPOINT}/foodDB
          password: ${TRAINING_DB_PASSWORD}
          username: datachan
          driver-class-name: org.postgresql.Driver
        jpa:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
          show-sql: false
          hibernate:
            ddl-auto: none
          properties:
            hibernate:
              temp:
                use_jdbc_metadata_defaults: false
              jdbc:
                lob:
                  non_contextual_creation: true
